name: Main Library CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        
    - name: Install dependencies
      run: |
        composer install
        composer require --dev alanvdb/symfony-console-application-test
        
    - name: Run tests
      run: ./vendor/bin/phpunit